name: Python application

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "pyc2ray/**.py"
      - "tests/**.py"
      - "src/**.f90"
      - "src/**.cu"
      - "src/**.cuh"
      - "**/meson.build"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install openMPI
      run: sudo apt install libopenmpi-dev

    - name: Install linters
      run: |
        pip install .[lint]

    - name: Check Python code format
      run: ruff format --check pyc2ray/ tests/

    - name: Check Python code style
      run: ruff check --extend-select I --output-format=concise pyc2ray/ tests/

    - name: Check Python code type annotations
      run: mypy pyc2ray/ tests/

    - name: Check C++ and CUDA code style
      run: find src/ -regex '.*\.\(cu\|cuh\|cpp\|h\)' -exec clang-format -n -Werror {} \;
